apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    labels:
        app: mongodb
        layer: database
        env: playground
    namespace: playground-ns
type: opaque
data:
    mongodb-root-user-name:
    mongodb-root-user-password:
