apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-deployment
    labels:
        app: mongodb
        layer: database
        env: playground
    namespace: playground-ns
spec:
    replicas: 2
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
                layer: database
                env: playground
        spec:
            containers:
            - name: mongodb
              image: mongo
              ports:
              - containerPort: 27017
              env:
              - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
                valueFrom:
                    configMapKeyRef:
                        name: mongodb-configmap
                        key: enable_admin  
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: mongodb-secret
                        key: mongodb-root-user-name
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mongodb-secret
                        key: mongodb-root-user-password
---
apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
    labels:
        app: mongodb
        layer: database
        env: playground
    namespace: playground-ns
spec:
    selector:
        app: mongodb
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
